import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const products = [
  {
    slug: "sea-doo-rxp-x-325",
    brand: "Sea-Doo",
    model: "RXP-X 325",
    year: 2025,
    priceCents: 2199000,
    power: 325,
    seats: 2,
    condition: "new",
    stock: 3,
    heroImage: "https://picsum.photos/seed/sea-doo-rxp-x-325/1200/900",
    gallery: "https://picsum.photos/seed/sea-doo-rxp-x-325/1600/1200,https://picsum.photos/seed/sea-doo-rxp-x-325-b/1600/1200,https://picsum.photos/seed/sea-doo-rxp-x-325-c/1600/1200",
    descriptionFr: "Le jetski le plus puissant de la gamme Sea-Doo. Châssis Ergolock T3-R et moteur Rotax 1630 ACE de 325 ch pour des sensations extrêmes.",
    descriptionEn: "The most powerful jetski in the Sea-Doo lineup. T3-R Ergolock hull and 325 hp Rotax 1630 ACE engine for extreme sensations.",
    descriptionDe: "Der leistungsstärkste Jetski der Sea-Doo-Reihe. T3-R-Ergolock-Rumpf und 325-PS-Rotax-1630-ACE-Motor für extreme Erlebnisse.",
    descriptionIt: "La moto d'acqua più potente della gamma Sea-Doo. Scafo T3-R Ergolock e motore Rotax 1630 ACE da 325 CV per sensazioni estreme.",
  },
  {
    slug: "yamaha-gp1800r-svho",
    brand: "Yamaha",
    model: "GP1800R SVHO",
    year: 2025,
    priceCents: 1899000,
    power: 250,
    seats: 3,
    condition: "new",
    stock: 5,
    heroImage: "https://picsum.photos/seed/yamaha-gp1800r/1200/900",
    gallery: "https://picsum.photos/seed/yamaha-gp1800r/1600/1200,https://picsum.photos/seed/yamaha-gp1800r-b/1600/1200,https://picsum.photos/seed/yamaha-gp1800r-c/1600/1200",
    descriptionFr: "Champion en titre des courses de jetski. Moteur SVHO suralimenté et coque NanoXcel2 ultra-légère.",
    descriptionEn: "Reigning jetski racing champion. SVHO supercharged engine and ultra-light NanoXcel2 hull.",
    descriptionDe: "Amtierender Champion im Jetski-Rennsport. SVHO-Kompressormotor und ultraleichter NanoXcel2-Rumpf.",
    descriptionIt: "Campione in carica delle corse di moto d'acqua. Motore SVHO sovralimentato e scafo NanoXcel2 ultraleggero.",
  },
  {
    slug: "kawasaki-ultra-310lx",
    brand: "Kawasaki",
    model: "Ultra 310LX",
    year: 2025,
    priceCents: 2399000,
    power: 310,
    seats: 3,
    condition: "new",
    stock: 2,
    heroImage: "https://picsum.photos/seed/kawasaki-ultra/1200/900",
    gallery: "https://picsum.photos/seed/kawasaki-ultra/1600/1200,https://picsum.photos/seed/kawasaki-ultra-b/1600/1200,https://picsum.photos/seed/kawasaki-ultra-c/1600/1200",
    descriptionFr: "Le luxe sur l'eau. Suspension JetSounds 4HP, système audio premium et 310 ch de puissance brute.",
    descriptionEn: "Luxury on water. JetSounds 4HP suspension, premium audio system and 310 hp of raw power.",
    descriptionDe: "Luxus auf dem Wasser. JetSounds 4HP-Federung, Premium-Audiosystem und 310 PS Rohleistung.",
    descriptionIt: "Lusso sull'acqua. Sospensione JetSounds 4HP, sistema audio premium e 310 CV di potenza pura.",
  },
  {
    slug: "sea-doo-gtx-limited-300",
    brand: "Sea-Doo",
    model: "GTX Limited 300",
    year: 2024,
    priceCents: 2589000,
    power: 300,
    seats: 3,
    condition: "new",
    stock: 4,
    heroImage: "https://boatingmag.com/wp-content/uploads/2021/09/btg1218-seadoo-gtx06-1024x682.jpg",
    gallery: "https://boatingmag.com/wp-content/uploads/2021/09/btg1218-seadoo-gtx06-1024x682.jpg,https://boatingmag.com/wp-content/uploads/2021/09/btg1218-seadoo-gtx05-1024x682.jpg,https://boatingmag.com/wp-content/uploads/2021/09/btg1218-seadoo-gtx08-1024x682.jpg,https://boatingmag.com/wp-content/uploads/2021/09/btg1218-seadoo-gtx02-1024x682.jpg",
    descriptionFr: "Le vaisseau-amiral touring de Sea-Doo. Moteur Rotax 1630 ACE 300 ch suralimenté, système iDF anti-débris, freinage intelligent iBR, écran tactile 7.8\", audio BRP Premium 100W et compartiment téléphone étanche. Capacité 3 places, rangement 27 gallons, finitions premium et selle Cruiser ergonomique pour les longues sorties.",
    descriptionEn: "The Sea-Doo touring flagship. Supercharged Rotax 1630 ACE 300 hp engine, iDF debris-free intake, iBR intelligent braking, 7.8\" touchscreen, 100W BRP Premium audio and waterproof phone compartment. 3-seater, 27-gallon storage, premium finishes and ergonomic Cruiser seat for long rides.",
    descriptionDe: "Das Touring-Flaggschiff von Sea-Doo. Aufgeladener Rotax 1630 ACE 300 PS Motor, iDF-Schmutzableitung, iBR intelligentes Bremssystem, 7,8\"-Touchscreen, 100W BRP Premium Audio und wasserdichtes Handyfach. 3 Sitze, 100 L Stauraum, Premium-Finish und ergonomischer Cruiser-Sitz für lange Touren.",
    descriptionIt: "L'ammiraglia da turismo Sea-Doo. Motore Rotax 1630 ACE 300 CV sovralimentato, sistema iDF anti-detriti, freno intelligente iBR, touchscreen 7,8\", audio BRP Premium 100W e vano telefono impermeabile. 3 posti, 100 L di stivaggio, finiture premium e sella Cruiser ergonomica per le uscite lunghe.",
  },
  {
    slug: "sea-doo-rxp-x-apex-300",
    brand: "Sea-Doo",
    model: "RXP-X Apex 300",
    year: 2024,
    priceCents: 2390000,
    power: 300,
    seats: 2,
    condition: "occasion",
    stock: 1,
    heroImage: "https://static.boatvertizer.com/fotos/yLyaGPnf/8298135-large.jpg",
    gallery: "https://static.boatvertizer.com/fotos/yLyaGPnf/8298135-large.jpg,https://static.boatvertizer.com/fotos/yLyaGPnf/8298134-large.jpg,https://static.boatvertizer.com/fotos/yLyaGPnf/8298143-large.jpg,https://static.boatvertizer.com/fotos/yLyaGPnf/8298138-large.jpg,https://static.boatvertizer.com/fotos/yLyaGPnf/8298144-large.jpg,https://static.boatvertizer.com/fotos/yLyaGPnf/8298137-large.jpg",
    descriptionFr: "Édition Apex limitée. Coque T3-R en carbone-injecté, X-Sponsons carbone, contrôle de lancement (Launch Control), siège racing ErgoLock R, amortisseur de direction hydraulique et écran couleur 7.8\" avec audio premium 100W BRP. Le RXP-X le plus radical jamais produit — pensé pour la course. Modèle 2024, 32 heures, état impeccable, housse de protection incluse, en provenance d'un revendeur certifié allemand.",
    descriptionEn: "Limited Apex edition. T3-R carbon-injected hull, carbon X-Sponsons, Launch Control, ErgoLock R racing seat, hydraulic steering damper and 7.8\" color display with 100W BRP premium audio. The most extreme RXP-X ever built — race-ready. 2024 model, 32 hours, pristine condition, protective cover included, from a certified German dealer.",
    descriptionDe: "Limitierte Apex-Edition. T3-R-Rumpf aus karbon-injiziertem Material, Karbon-X-Sponsons, Launch Control, ErgoLock R-Rennsitz, hydraulischer Lenkungsdämpfer und 7,8\"-Farbdisplay mit 100W BRP Premium-Audio. Der radikalste RXP-X aller Zeiten — renntauglich. Modell 2024, 32 Stunden, neuwertiger Zustand, Schutzhülle inklusive, von einem zertifizierten deutschen Händler.",
    descriptionIt: "Edizione Apex limitata. Scafo T3-R in materiale carbo-iniettato, X-Sponsons in carbonio, Launch Control, sella racing ErgoLock R, ammortizzatore di sterzo idraulico e display a colori da 7,8\" con audio BRP Premium da 100W. Il RXP-X più estremo mai prodotto — pronto per la pista. Modello 2024, 32 ore, condizioni impeccabili, telo di protezione incluso, da un rivenditore certificato tedesco.",
  },
  {
    slug: "yamaha-fx-cruiser-svho",
    brand: "Yamaha",
    model: "FX Cruiser SVHO",
    year: 2025,
    priceCents: 1999000,
    power: 250,
    seats: 3,
    condition: "new",
    stock: 6,
    heroImage: "https://picsum.photos/seed/yamaha-fx/1200/900",
    gallery: "https://picsum.photos/seed/yamaha-fx/1600/1200,https://picsum.photos/seed/yamaha-fx-b/1600/1200,https://picsum.photos/seed/yamaha-fx-c/1600/1200",
    descriptionFr: "Confort et performance. Écran 7 pouces couleur, RiDE intuitif et siège Cruiser ergonomique.",
    descriptionEn: "Comfort and performance. 7-inch color screen, intuitive RiDE and ergonomic Cruiser seat.",
    descriptionDe: "Komfort und Leistung. 7-Zoll-Farbdisplay, intuitives RiDE und ergonomischer Cruiser-Sitz.",
    descriptionIt: "Comfort e prestazioni. Schermo a colori da 7 pollici, RiDE intuitivo e sella Cruiser ergonomica.",
  },
  {
    slug: "kawasaki-stx-160",
    brand: "Kawasaki",
    model: "STX 160",
    year: 2024,
    priceCents: 1299000,
    power: 160,
    seats: 3,
    condition: "new",
    stock: 8,
    heroImage: "https://picsum.photos/seed/kawasaki-stx/1200/900",
    gallery: "https://picsum.photos/seed/kawasaki-stx/1600/1200,https://picsum.photos/seed/kawasaki-stx-b/1600/1200,https://picsum.photos/seed/kawasaki-stx-c/1600/1200",
    descriptionFr: "Le meilleur rapport qualité-prix. Polyvalent, fiable et accessible pour toute la famille.",
    descriptionEn: "Best value for money. Versatile, reliable and accessible for the whole family.",
    descriptionDe: "Bestes Preis-Leistungs-Verhältnis. Vielseitig, zuverlässig und für die ganze Familie zugänglich.",
    descriptionIt: "Miglior rapporto qualità-prezzo. Versatile, affidabile e accessibile a tutta la famiglia.",
  },
  {
    slug: "sea-doo-spark-trixx-90",
    brand: "Sea-Doo",
    model: "Spark Trixx 90",
    year: 2025,
    priceCents: 899000,
    power: 90,
    seats: 2,
    condition: "new",
    stock: 10,
    heroImage: "https://picsum.photos/seed/sea-doo-spark/1200/900",
    gallery: "https://picsum.photos/seed/sea-doo-spark/1600/1200,https://picsum.photos/seed/sea-doo-spark-b/1600/1200,https://picsum.photos/seed/sea-doo-spark-c/1600/1200",
    descriptionFr: "Léger, joueur, ultra-maniable. Le jetski parfait pour les figures freestyle.",
    descriptionEn: "Light, playful, ultra-maneuverable. The perfect jetski for freestyle tricks.",
    descriptionDe: "Leicht, verspielt, ultra-wendig. Der perfekte Jetski für Freestyle-Tricks.",
    descriptionIt: "Leggera, divertente, ultra-manovrabile. La moto d'acqua perfetta per le acrobazie freestyle.",
  },
  {
    slug: "yamaha-superjet",
    brand: "Yamaha",
    model: "SuperJet",
    year: 2024,
    priceCents: 1199000,
    power: 100,
    seats: 1,
    condition: "occasion",
    stock: 1,
    heroImage: "https://picsum.photos/seed/yamaha-superjet/1200/900",
    gallery: "https://picsum.photos/seed/yamaha-superjet/1600/1200,https://picsum.photos/seed/yamaha-superjet-b/1600/1200,https://picsum.photos/seed/yamaha-superjet-c/1600/1200",
    descriptionFr: "Le mythique stand-up Yamaha. 2024, peu utilisé, parfait état. Pour pilotes confirmés.",
    descriptionEn: "The legendary Yamaha stand-up. 2024, lightly used, perfect condition. For experienced riders.",
    descriptionDe: "Der legendäre Yamaha Stand-up. 2024, kaum gebraucht, perfekter Zustand. Für erfahrene Fahrer.",
    descriptionIt: "La leggendaria stand-up Yamaha. 2024, poco usata, condizioni perfette. Per piloti esperti.",
  },
];

async function main() {
  console.log("Seeding...");
  for (const p of products) {
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
  }
  console.log(`Seeded ${products.length} products.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
